# docker-compose.yml
version: '3.7'
services:
  app:
    build:
      context: .
      target: builder
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 4000
    ports:
      - '4000:4000'
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
